### ISSUE TITLE
raynet_forward for the end-to-end testing generates an error

### ISSUE THREAD

**Issue by cecca46** [paschalidoud/raynet#4]
Hello,
I am trying to run raynet_forward after the end-to-end traininf on the restrepo dataset. The command I am runnng is:

raynet_forward ./probabilistic_reconstruction_data ./RES/FinalRun/depth_FromMRF/ --weight_file ./RES/FinalRun/Raynet_end_to_end/weights.6.hdf5 --scene_idx 2 --network_architecture simple_cnn --forward_pass_factory raynet --dataset_type restrepo --start_end 0,20

This command generates the following error. Any suggestions?

Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14782 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
{0: 'BH', 1: 'capitol', 2: 'downtown'}
Saving stuff to random directory /tmp/tmpOBA9E1 ..
Iteration 0 
Features computation -  3.633902
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/cecca4624/.local/bin/raynet_forward", line 9, in <module>
    load_entry_point('raynet', 'console_scripts', 'raynet_forward')()
  File "/home/cecca4624/RaynetData/raynet/raynet/scripts/forward_pass.py", line 136, in main
    for S in depth_images:
  File "/home/cecca4624/RaynetData/raynet/raynet/forward_pass.py", line 664, in forward_pass
    ray_to_occupancy_messages_pon[i:i+batch_size] = msgs.get()
  File "/usr/local/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 305, in get
    _memcpy_discontig(ary, self, async_=async_, stream=stream)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 1309, in _memcpy_discontig
    drv.memcpy_dtoh(dst, src.gpudata)
pycuda._driver.LogicError: cuMemcpyDtoH failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered

**Comment by cecca46** [comment]
It was just a dimensionality problem, the error was fixed by changing the number of ray for each batch.
